-- File: PA.vhd
-- Generated by MyHDL 0.11
-- Date: Tue Dec 14 16:16:59 2021


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_011.all;

entity PA is
    port (
        acc: out unsigned(10 downto 0);
        count: in unsigned(31 downto 0);
        p_off: in unsigned(31 downto 0);
        enable: in std_logic;
        clock: in std_logic;
        reset: in std_logic
    );
end entity PA;
-- Phase accumulation.
-- acc -- wave samples index
-- count --  incrementer output
-- p_off -- phase offset
-- enable -- control input
-- clock -- clock input
-- reset -- asynchronous reset input

architecture MyHDL of PA is




begin




PA_SEQ: process (clock, reset) is
begin
    if (reset = '1') then
        acc <= to_unsigned(0, 11);
    elsif rising_edge(clock) then
        if bool(enable) then
            acc <= resize((count + p_off)(33-1 downto 21), 11);
        end if;
    end if;
end process PA_SEQ;

end architecture MyHDL;
